CLIENT_ID="07bb871c-d82a-43db-9d1f-3ed7382dc680"
SECRET="57a61435-64ef-49e5-8ea5-baadca79cc3f"


AUTHORIZATION_KEY="MDdiYjg3MWMtZDgyYS00M2RiLTlkMWYtM2VkNzM4MmRjNjgwOmEwMjcyZDE5LTIxZGMtNDk2NS05YmEzLTY0MjY0NDdkYjlmMw=="